### ISSUE TITLE
Crash when placing a buildable (potentially related to `AFGBuildable::GetRainOcclusionShape`)

### ISSUE THREAD

**Issue by Popax21** [Panakotta00/FicsIt-Networks#367] opened 2024-11-29 05:45 UTC
When placing a buildable like e.g. a computer case / network router on latest Satisfactory stable (v1.0.1.0, released today) with latest Ficsit networks (v0.3.30), the game crashes (usually because of null pointer dereferences, but I have also seen memory allocation-related failures). In both cases, the stacktrace seens to indicate that something goes wrong while calling `AFGBuildable::GetRainOcclusionShape` at the start of the build animation, which might indicate that this patch changed something about how rain occlusion works in Satisfactory.

Example scrash nr. 1 (result of placing a computer case):
```
> Crash message:
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION writing address 0x0000000000000000

> Stack trace:
FactoryGameSteam-FactoryGame-Win64-Shipping + 00762f3d: TSizedHeapAllocator<32,FMemory>::ForAnyElementType::{ctor} [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Core\Public\Containers\ContainerAllocationPolicies.h:514:0]
FactoryGameSteam-FactoryGame-Win64-Shipping + 00138484: AFGBuildable::GetRainOcclusionShape(void) [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Public\Buildables\FGBuildable.h:511:0]
FactoryGameSteam-FactoryGame-Win64-Shipping + 003f82c1: AFGBuildable::OnRep_CustomizationData(void) [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\Buildables\FGBuildable.cpp:1032:0]
FactoryGameSteam-FactoryGame-Win64-Shipping + 003e1dab: AFGBuildable::BeginPlay(void) [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\Buildables\FGBuildable.cpp:453:0]
FactoryGameSteam-FicsItNetworksComputer-Win64-Shipping + 00063887: AFINComputerCase::BeginPlay(void) [C:\CI\_work\FicsIt-Networks\FicsIt-Networks\SatisfactoryModLoader\Mods\FicsItNetworks\Source\FicsItNetworksComputer\Private\FINComputerCase.cpp:109:0]
FactoryGameSteam-Engine-Win64-Shipping + 003b1a40
FactoryGameSteam-FactoryGame-Win64-Shipping + 00828683: AFGBuildableHologram::Construct(class TArray<class AActor *, class TSizedDefaultAllocator<32>> &, struct FNetConstructionID) [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\Hologram\FGBuildableHologram.cpp:718:0]
FactoryGameSteam-FactoryGame-Win64-Shipping + 004cc7f6: UFGBuildGunStateBuild::InternalConstructHologram(struct FNetConstructionID) [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\Equipment\FGBuildGunBuild.cpp:1744:0]
FactoryGameSteam-FactoryGame-Win64-Shipping + 004d8adc: TArray<unsigned char,TSizedDefaultAllocator<32> >::{dtor} [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Core\Public\Containers\Array.h:696:0]
FactoryGameSteam-FactoryGame-Win64-Shipping + 001d45c1: TArray<unsigned char,TSizedDefaultAllocator<32> >::{dtor} [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Core\Public\Containers\Array.h:696:0]
FactoryGameSteam-CoreUObject-Win64-Shipping + 00102949
FactoryGameSteam-CoreUObject-Win64-Shipping + 0028571e
FactoryGameSteam-FactoryGame-Win64-Shipping + 001d2451: TArray<unsigned char,TSizedDefaultAllocator<32> >::{dtor} [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Core\Public\Containers\Array.h:696:0]
FactoryGameSteam-FactoryGame-Win64-Shipping + 004cdbcf: UFGBuildGunStateBuild::InternalExecuteDuBuildStepInput(bool) [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\Equipment\FGBuildGunBuild.cpp:1063:0]
FactoryGameSteam-CoreUObject-Win64-Shipping + 00102949
FactoryGameSteam-CoreUObject-Win64-Shipping + 002762c3
```

Example crash nr. 2 (result of placing a network router):
```
> Crash message:
Fatal error: [File:C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Core\Private\HAL\MallocBinned2.cpp] [Line: 1438] 
FMallocBinned2 Attempt to realloc an unrecognized block 0000000119840000   canary == 0x0 != 0xe3

> Stack trace
kernelbase + 00068ee6
FactoryGameSteam-Core-Win64-Shipping + 00200ed8
FactoryGameSteam-Core-Win64-Shipping + 00200ad3
FactoryGameSteam-Core-Win64-Shipping + 00200cdd
FactoryGameSteam-Core-Win64-Shipping + 002b5369
FactoryGameSteam-Win64-Shipping + 0001fd90
VCRUNTIME140 + 0000f0e0
ntdll + 0000f284
ntdll + 000422d3
ntdll + 00044c57
ntdll + 0000f2b6
FactoryGameSteam-AbstractInstance-Win64-Shipping + 00009ae0: TArray<FInstanceData,TSizedDefaultAllocator<32> >::{ctor} [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Core\Public\Containers\Array.h:467:0]
FactoryGameSteam-FactoryGame-Win64-Shipping + 00762fd3: TArray<FInstanceData,TSizedDefaultAllocator<32> >::end [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Core\Public\Containers\Array.h:2838:0]
FactoryGameSteam-FactoryGame-Win64-Shipping + 00138484: AFGBuildable::GetRainOcclusionShape(void) [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Public\Buildables\FGBuildable.h:511:0]
FactoryGameSteam-FactoryGame-Win64-Shipping + 003f82c1: AFGBuildable::OnRep_CustomizationData(void) [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\Buildables\FGBuildable.cpp:1032:0]
FactoryGameSteam-FactoryGame-Win64-Shipping + 003e1dab: AFGBuildable::BeginPlay(void) [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\Buildables\FGBuildable.cpp:453:0]
FactoryGameSteam-FicsItNetworksCircuit-Win64-Shipping + 00026a89: AFINNetworkRouter::BeginPlay(void) [C:\CI\_work\FicsIt-Networks\FicsIt-Networks\SatisfactoryModLoader\Mods\FicsItNetworks\Source\FicsItNetworksCircuit\Private\Buildables\FINNetworkRouter.cpp:23:0]
FactoryGameSteam-Engine-Win64-Shipping + 003b1a40
FactoryGameSteam-FactoryGame-Win64-Shipping + 00828683: AFGBuildableHologram::Construct(class TArray<class AActor *, class TSizedDefaultAllocator<32>> &, struct FNetConstructionID) [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\Hologram\FGBuildableHologram.cpp:718:0]
FactoryGameSteam-FactoryGame-Win64-Shipping + 004cc7f6: UFGBuildGunStateBuild::InternalConstructHologram(struct FNetConstructionID) [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\Equipment\FGBuildGunBuild.cpp:1744:0]
FactoryGameSteam-FactoryGame-Win64-Shipping + 004d8adc: TArray<unsigned char,TSizedDefaultAllocator<32> >::{dtor} [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Core\Public\Containers\Array.h:696:0]
FactoryGameSteam-FactoryGame-Win64-Shipping + 001d45c1: TArray<unsigned char,TSizedDefaultAllocator<32> >::{dtor} [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Core\Public\Containers\Array.h:696:0]
FactoryGameSteam-CoreUObject-Win64-Shipping + 00102949
FactoryGameSteam-CoreUObject-Win64-Shipping + 0028571e
FactoryGameSteam-FactoryGame-Win64-Shipping + 001d2451: TArray<unsigned char,TSizedDefaultAllocator<32> >::{dtor} [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Core\Public\Containers\Array.h:696:0]
FactoryGameSteam-FactoryGame-Win64-Shipping + 004cdbcf: UFGBuildGunStateBuild::InternalExecuteDuBuildStepInput(bool) [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\Equipment\FGBuildGunBuild.cpp:1063:0]
```

**Comment by Panakotta00** [comment] 2024-11-29 11:07
Jeah that issue is caused by a VTable mismatch introduced with the latest game update. It will be fixed with the next update.

**Closed** 2024-11-30 23:41 UTC
Labels: bug
