### ISSUE TITLE
Wrong snappoint for wall plug on bottom of foundation

### ISSUE THREAD

**Issue by DjCHI** [Panakotta00/FicsIt-Networks#244] opened 2022-12-13 23:17 UTC
If you try to place a wall plug on the bottom of a foundation, the connector is placed on the upper side of the foundation, but upside down.

SatisFactory Early Access with Update 7
FIN Version 0.3.12

![Screenshot (180)](https://user-images.githubusercontent.com/120527110/207465586-f0a95eb1-b3f5-4fbc-a461-b0675d76c81a.png)

**Comment by M-Marvin** [comment] 2022-12-22 20:08
Also the connector have a different placement behavior compared to the power connector.
It cant be placed on beams and some other things that are valid for power connectors.
Im not sure how the placement is implemented, but maybe the behavior can be copied directly from the power connectors ?

![image](https://user-images.githubusercontent.com/69386758/209217337-16cd2b45-369c-4724-926c-a1b134b13488.png)

**Comment by Panakotta00** [comment] 2022-12-22 23:01
@M-Marvin 
> Also the connectors have a different placement behavior compared to the power connector. It cant be placed on beams and some other things that are valid for power connectors. Im not sure how the placement is implemented, but maybe the behavior can be copied directly from the power connectors ?
> 
> ![image](https://user-images.githubusercontent.com/69386758/209217337-16cd2b45-369c-4724-926c-a1b134b13488.png)

It's not related, so duplicate of #208

**Comment by M-Marvin** [comment] 2022-12-23 00:28
Oh, did notice that this issue was still there, i thought it got removed ore something, but i just filtered out enhancements.
(Did not expect that it got tagged as enhancement)

**Closed** 2023-08-30 19:18 UTC
Labels: bug
